---
- name: Manage OpenAFS buildbot master
  hosts: openafs_buildbot_masters
  collections:
    - openafs_contrib.buildbot
  tasks:
    - import_role:
        name: buildbot_master

    - name: "Update README file."
      template:
        src: README.j2
        dest: README
        mode: "0644"

    - name: "Log snapshot."
      command:
        cmd: "cp twistd.log twistd-snapshot.log"
        chdir: "{{ buildbot_master_basedir }}"
      check_mode: no
      changed_when: false
      when: buildbot_master_download_log | d('no') | bool

    - name: "Download log."
      fetch:
        src: "{{ buildbot_master_basedir }}/twistd-snapshot.log"
        dest: logs
      when: buildbot_master_download_log | d('no') | bool
